@Host = http://localhost:5037

###
# Valid and solved, returns 200
POST {{Host}}/validate
Accept: application/json
Content-Type: application/json

[
    1,2,3, 4,5,6, 7,8,9,
    4,5,6, 7,8,9, 1,2,3,
    7,8,9, 1,2,3, 4,5,6,

    2,3,1, 5,6,4, 8,9,7,
    5,6,4, 8,9,7, 2,3,1,
    8,9,7, 2,3,1, 5,6,4,

    3,1,2, 6,4,5, 9,7,8,
    6,4,5, 9,7,8, 3,1,2,
    9,7,8, 3,1,2, 6,4,5
]

###
# Valid and unsolved, returns 200
POST {{Host}}/validate
Accept: application/json
Content-Type: application/json

[
    1,2,3, 4,5,6, 7,8,9,
    4,5,6, 7,8,9, 1,2,3,
    7,8,9, 1,2,3, 4,5,6,

    2,3,1, 5,6,4, 8,9,7,
    5,6,4, 8,9,7, 2,3,1,
    8,9,7, 2,3,1, 5,6,4,

    3,1,2, 6,4,5, 9,7,8,
    6,4,5, 9,7,8, 3,1,2,
    9,7,8, 3,null,2, 6,4,5
]

###
# Invalid with solved as null, returns 200
POST {{Host}}/validate
Accept: application/json
Content-Type: application/json

[
    1,2,3, 4,5,6, 7,8,9,
    4,5,6, 7,8,9, 1,2,3,
    7,8,9, 1,2,3, 4,5,6,

    2,3,1, 5,6,4, 8,9,7,
    5,6,4, 8,9,7, 2,3,1,
    8,9,7, 2,3,1, 5,6,4,

    3,1,2, 6,4,5, 9,7,8,
    6,4,5, 9,7,8, 3,1,2,
    1,7,8, 3,1,2, 6,4,5
]

###
# Bad request
POST {{Host}}/validate
Accept: application/json
Content-Type: application/json

[ 1 ]

###
# 400
POST {{Host}}/set
Accept: application/json
Content-Type: application/json

{
    "board": [
        1,2,3, 4,5,6, 7,8,9,
        4,5,6, 7,8,9, 1,2,3,
        7,8,9, 1,2,3, 4,5,6,

        2,3,1, 5,6,4, 8,9,7,
        5,6,4, 8,9,7, 2,3,1,
        8,9,7, 2,3,1, 5,6,4,

        3,1,2, 6,4,5, 9,7,8,
        6,4,5, 9,7,8, 3,1,2,
        9,7,8, 3,null,2, 6,4,5
    ],
    "row": 8,
    "column": 4,
    "value": 1
}


###
POST {{Host}}/set
Accept: application/json
Content-Type: application/json

{
    "board": [
        1,2,3, 4,5,6, 7,8,9,
        4,5,6, 7,8,9, 1,2,3,
        7,8,9, 1,2,3, 4,5,6,

        2,3,1, 5,6,4, 8,9,7,
        5,6,4, 8,9,7, 2,3,1,
        8,9,7, 2,3,1, 5,6,4,

        3,1,2, 6,4,5, 9,7,8,
        6,4,5, 9,7,8, 3,1,2,
        9,7,8, 3,1,2, 6,4,5
    ],
    "row": 8,
    "column": 4,
    "value": 1
}