GET http://localhost:5104/ping

###
POST http://localhost:5104/add
Content-Type: application/json
    
{
    "a": 1,
    "b": 2
}

###
GET http://localhost:5104/sub?a=5&b=2

###
GET http://localhost:5104/customers

###
GET http://localhost:5104/customers/1

